# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:3.6

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V # Print out python version for debugging
  - pip install pipx
  - export PATH=$PATH:/root/.local/bin
  - pipx install poetry
  - pipx install tox
  - poetry install

test:
  script:
    - source $(poetry env info --path)/bin/activate
    - poetry run pytest
    - tox -e py36,flake8

# run:
#   script:
#     - poetry build
#   artifacts:
#     paths:
#       - dist/*.whl

pages:
  script:
    - pip install sphinx sphinx-rtd-theme
    - cd doc ; make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  # only:
  #   - master
