name: Dependency Review

on:
  pull_request: {}
  workflow_dispatch:
    inputs: {}

permissions:
  contents: read

jobs:
  dependency-review:
    name: Check for vulnerable dependencies and invalid licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: actions/dependency-review-action@bc41886e18ea39df68b1b1245f4184881938e050 # v4.7.2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          fail-on-severity: high
